services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    restart: no
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connections,error},{default,error}] disk_free_limit 2147483648 -rabbitmq_prometheus listener [{port,15692}]
    volumes:
       - ./services/rabbitmq:/var/lib/rabbitmq  
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15692:15692"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./services/grafana:/var/lib/grafana
      - ./services/grafanaedit:/etc/grafana/provisioning
      - ./services/grafanainit/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus