global:
  # Время ожидания перед повторной отправкой уведомления
  resolve_timeout: 5m

# Каналы для отправки уведомлений (по умолчанию пустые)
route:
  # Группировать уведомления по алертам с одинаковыми labels
  group_by: ['alertname']
  # Время ожидания перед отправкой первой группы уведомлений
  group_wait: 30s
  # Время ожидания перед отправкой уведомлений о новых алертах в группе
  group_interval: 5m
  # Время между повторными отправками уведомлений
  repeat_interval: 4h
  # Получатель по умолчанию (если не указаны другие маршруты)
  receiver: 'null'

receivers:
- name: 'null'

# Отключение подавления уведомлений по умолчанию
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
